### ISSUE TITLE
Improve mobile display

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/opencodelists#18]
This may be related to the temporary web hosting but there a few bugs with mobile display. It would be great to optimise display so the browse feature works well. Download etc is more relevant for people work on desktops/large display. This might be said about users overall but I would've said that about OpenPrescribing and the good mobile interface on that has changed my practice and I use it a lot on the mobile when having discussions or in meetings (where I don't have my computer to hand).

![image](https://user-images.githubusercontent.com/40460354/80280797-4f642600-86fe-11ea-824f-6d5318d54ea6.png)

**Comment by inglesp** [comment]
Fixed in beed78c9.

![Screen Shot 2020-04-30 at 10 22 15](https://user-images.githubusercontent.com/28734/80694616-a71eda80-8acc-11ea-9c3f-1d07bd95c8f4.png)

**Comment by inglesp** [comment]
Maybe "improved" rather than "fixed", but we can revisit this.

**Comment by brianmackenna** [comment]
I just checked on Android mobile and tablet devices and I think fixed is accurate description!
